=== sriharikrishna/xaifBooster/tools/codegen/xml/CodeGenerator.xsd
<?xml version="1.0" encoding="UTF-8"?> 

<!-- *********************************************************** -->
<!-- Code Generator			                         -->
<!-- Uwe Naumann                                                 -->
<!-- MCS, ANL, 2003                                              -->
<!-- *********************************************************** -->

<xsd:schema xmlns="http://www.mcs.anl.gov/CodeGen"
	    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://www.mcs.anl.gov/CodeGen"
	    xmlns:CodeGen="http://www.mcs.anl.gov/CodeGen"
            version="Code Generator"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">       

<!-- *********************************************************** -->
<!-- Document -->
<!-- *********************************************************** -->

<xsd:complexType name="DocumentType" mixed="true">
  <xsd:choice minOccurs="1" maxOccurs="unbounded">
    <xsd:element name="NonRepeatableCodeOrLineBreak">
      <xsd:complexType>
        <xsd:attribute name="text" type="xsd:string" use="optional"/>
      </xsd:complexType>
    </xsd:element>
    <xsd:element name="RepeatableCode" type="RepeatableCodeType"/>
  </xsd:choice>
  <xsd:attribute name="nr_entries" type="xsd:positiveInteger" use="required"/>
  <xsd:attribute name="nr_templates" type="xsd:positiveInteger" use="required"/>
  <xsd:attribute name="outfile" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:element name="Document" type="DocumentType"/>

<!-- *********************************************************** -->
<!-- RepeatableCode -->
<!-- *********************************************************** -->

<xsd:complexType name="RepeatableCodeType" mixed="true">
  <xsd:sequence> 
    <xsd:element name="CodeTemplate" type="CodeTemplateType"/>
    <xsd:element name="CodeVersion" type="CodeVersionType" minOccurs="0" maxOccurs="unbounded"/>
  </xsd:sequence> 
  <xsd:attribute name="nr_versions" type="xsd:positiveInteger" use="required"/>
  <xsd:attribute name="use_versions" type="xsd:integer" use="optional" default="-1"/>
</xsd:complexType>


<!-- *********************************************************** -->
<!-- CodeTemplate -->
<!-- *********************************************************** -->

<xsd:complexType name="CodeTemplateType" mixed="true">
  <xsd:choice minOccurs="1" maxOccurs="unbounded">
    <xsd:element name="StaticCode">
      <xsd:complexType>
        <xsd:attribute name="text" type="xsd:string" use="required"/>
      </xsd:complexType>
    </xsd:element>
    <xsd:element name="DynamicCodePlaceholder">
      <xsd:complexType>
        <xsd:attribute name="hook" type="xsd:string" use="required"/>
      </xsd:complexType>
    </xsd:element>
    <xsd:element name="LineBreak"/>
  </xsd:choice>
  <xsd:attribute name="nr_entries" type="xsd:positiveInteger" use="required"/>
</xsd:complexType>

<!-- *********************************************************** -->
<!-- CodeVersionType -->
<!-- *********************************************************** -->

<xsd:complexType name="CodeVersionType" mixed="true">
  <xsd:sequence> 
    <xsd:element name="DynamicCode" minOccurs="0" maxOccurs="unbounded">
      <xsd:complexType>
        <xsd:attribute name="hook_ref" type="xsd:string" use="required"/>
        <xsd:attribute name="text" type="xsd:string" use="required"/>
      </xsd:complexType>
    </xsd:element>
  </xsd:sequence> 
</xsd:complexType>

</xsd:schema>

=== sriharikrishna/xaifBooster/tools/codegen/xml/parse_method_decl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- UN-10-27-03 -->

<CodeGen:Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:CodeGen="http://www.mcs.anl.gov/CodeGen"
       xsi:schemaLocation="http://www.mcs.anl.gov/CodeGen CodeGenerator.xsd"
       nr_entries="1" nr_templates="1" outfile="parse_method_decl.inc">

  <CodeGen:RepeatableCode nr_versions="41">
    <CodeGen:CodeTemplate nr_entries="4">
      <CodeGen:StaticCode text="void on"/>
      <CodeGen:DynamicCodePlaceholder hook="3"/>
      <CodeGen:StaticCode text="(const XAIFBaseParserHelper&#38; passingIn, XAIFBaseParserHelper&#38; passingOut);"/>
      <CodeGen:LineBreak/>
    </CodeGen:CodeTemplate>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="AliasMapEntry"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="AliasMap"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="AliasRange"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="AliasSingle"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Argument"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ArgumentList"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ArgumentSymbolReference"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ArrayAccess"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ArrayIndex"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Assignment"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="AssignmentLHS"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="AssignmentRHS"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="BasicBlock"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="BooleanOperation"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="CallGraph"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="CallGraphEdge"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Condition"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Constant"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ControlFlowGraph"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ControlFlowGraphEdge"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Entry"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Exit"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ExpressionEdge"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ForLoop"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="IfStatement"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Initialization"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Intrinsic"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Marker"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="PostLoop"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="PreLoop"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Scope"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="ScopeContainment"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Scopes"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="SubroutineCall"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="SymbolReference"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Symbol"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="SymbolTable"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Update"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Variable"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="VariableEdge"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="3" text="Dummy"/>
    </CodeGen:CodeVersion>
  </CodeGen:RepeatableCode>
</CodeGen:Document>

=== sriharikrishna/xaifBooster/tools/codegen/xml/helper_initialization.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- UN-10-27-03 -->

<CodeGen:Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:CodeGen="http://www.mcs.anl.gov/CodeGen"
       xsi:schemaLocation="http://www.mcs.anl.gov/CodeGen CodeGenerator.xsd"
       nr_entries="3" nr_templates="1" outfile="helper_initialization.inc">

  <CodeGen:RepeatableCode nr_versions="35">
    <CodeGen:CodeTemplate nr_entries="4">
      <CodeGen:StaticCode text="my"/>
      <CodeGen:DynamicCodePlaceholder hook="1"/>
      <CodeGen:StaticCode text="_p(0),"/>
      <CodeGen:LineBreak/>
    </CodeGen:CodeTemplate>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="AliasMap"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="AliasMapEntry"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="ArgumentList"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="ArrayAccess"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Assignment"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="BaseLoop"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="BasicBlock"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Branch"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="CallGraph"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="ConcreteArgument"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Condition"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="ControlFlowGraph"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="DoMap"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="DuUdMap"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Expression"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="ExpressionEdge"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="ForLoop"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Goto"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="IfStatement"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="IndexTriplet"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Initialization"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Label"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="PostLoop"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="PreLoop"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Scope"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Scopes"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="SideEffectList"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="StatementIdSetMap"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="StatementIdSetMapEntry"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="SubroutineCall"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Symbol"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="SymbolReferenceProperty"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="SymbolTable"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Update"/>
    </CodeGen:CodeVersion>
    <CodeGen:CodeVersion>
      <CodeGen:DynamicCode hook_ref="1" text="Variable"/>
    </CodeGen:CodeVersion>
  </CodeGen:RepeatableCode>
<!-- last entry is not succeeded by a comma -->
  <CodeGen:NonRepeatableCodeOrLineBreak text="myVariableEdge_p(0)"/>
  <CodeGen:NonRepeatableCodeOrLineBreak/>

</CodeGen:Document>
